name: k24
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  animations: ^2.0.7
  convex_bottom_bar: ^3.2.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_launcher_icons: ^0.11.0
  get: 4.6.5
  intl: ^0.18.0
  lottie: ^2.2.0
  path_provider: ^2.0.12
  sliding_up_panel: ^2.0.0+1
  sqflite: ^2.2.4+1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  
flutter:
  assets:
    - assets/lottie/
  uses-material-design: true
